### ISSUE TITLE
Launching doesn't make a new build?

### ISSUE THREAD

**Issue by Torguen** [godotengine/godot-csharp-vscode#18]
3.3.2 stable mono oficial

**OS/device including version:**

win10  64

**Issue description:**

I am using "launch" but a new version is not created with my new code.
It seems that launching does not recompile the game and execute this new version, am I wrong?

**Screenshots of issue:**

**Comment by raulsntos** [comment]
You are right, it does not build the game, it only executes it. I actually prefer it that way because then I can just launch the game without having to recompile everytime. To get the behavior you are looking for you can add a `preLaunchTask`:

**.vscode/launch.json**
```json
{
	"version": "0.2.0",
	"configurations": [
		{
			"name": "Launch",
			"type": "godot-mono",
			"request": "launch",
			"mode": "executable",
			"preLaunchTask": "build",
			"executable": "godot",
			"executableArguments": [
				"--path",
				"${workspaceRoot}"
			]
		}
	]
},
```

**.vscoded/tasks.json**
```json
{
	// See https://go.microsoft.com/fwlink/?LinkId=733558
	// for the documentation about the tasks.json format
	"version": "2.0.0",
	"tasks": [
		{
			"label": "build",
			"type": "shell",
			"command": "msbuild",
			"args": [
				// Ask msbuild to generate full paths for file names.
				"/property:GenerateFullPaths=true",
				"/t:build",
				// Do not generate summary otherwise it leads to duplicate errors in Problems panel
				"/consoleloggerparameters:NoSummary"
			],
			"group": "build",
			"presentation": {
				// Reveal the output only if unrecognized errors occur.
				"reveal": "silent"
			},
			// Use the standard MS compiler pattern to detect errors, warnings and infos
			"problemMatcher": "$msCompile"
		}
	]
}
```

This build task was generated by vscode:

1. Open the Command Palette (Ctrl + Shift + P) and select `Tasks: Configure Task`
![image](https://user-images.githubusercontent.com/3903059/126776381-75231f56-414c-4b74-80bb-f06b3be76a5c.png)

2. Select `Create tasks.json file from template`
![image](https://user-images.githubusercontent.com/3903059/126776424-4716d511-2eed-46c7-803e-31343102d262.png)

3. Select `MSBuild` or `.NET Core` (If not sure take a look at which `Build tool` is selected in Godot Editor settings, I think the default is `dotnet CLI` so `.NET Core`)
![image](https://user-images.githubusercontent.com/3903059/126776455-b51cdaea-ee34-4c16-912c-64c1934d8004.png)

**Comment by Torguen** [comment]
Where did that come from? I never did tha
![Captura2](https://user-images.githubusercontent.com/19652075/141750997-04566a3e-b116-4b05-a36f-04690dce9075.PNG)
t.

**Comment by raulsntos** [comment]
It's automatically done by Github when creating an issue, it's specified in the template: 

https://github.com/godotengine/godot-csharp-vscode/blob/d573a970bf7efbeb873c73fc49204f12ab77a064/.github/ISSUE_TEMPLATE/bug-report.md?plain=1#L5-L6
